server:
  port: ${PORT:8088} 
spring:
  application:
    name: spring-challenge   
  datasource:
    url: jdbc:h2:./db/challenge-db
    username: newuser
    password: somepassword 
  sql:
    init:  
      mode: always
      schema-locations: classpath:initial-schema.sql  
      data-locations: classpath:initial-data.sql 
  h2:
    console: 
      enabled: true
      path: /administration/db-console