server:
  port: ${PORT:8088}
  error:
      include-message: always

logging:
  level:
    org:
      springframework:
        web=: DEBUG

spring:
  application:
    name: spring-challenge   
  datasource:
    url: jdbc:h2:./db/challenge-db
    username: newuser
    password: somepassword 
  sql:
    init:  
      mode: always
      schema-locations: classpath:initial-schema.sql  
      data-locations: classpath:initial-data.sql 
  h2:
    console:
      enabled: true
      path: /administration/db-console
service:
  sms:
    name: sms-service
    url: https://sms.vanso.com/rest/sms
    username: test-challenge
    password: HwR7F1Oe
    timeIntervalBetweenRequestsInMilliSeconds: 1_100

