DROP TABLE IF EXISTS PUBLIC.USER_ENTITY;

CREATE TABLE PUBLIC.USER_ENTITY (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EMAIL CHARACTER VARYING(255),
  FIRST_NAME CHARACTER VARYING(255),
  LAST_NAME CHARACTER VARYING(255),
  PHONE CHARACTER VARYING(255),
  CONSTRAINT CONSTRAINT_F PRIMARY KEY (ID)
);
CREATE INDEX IDX4XAD1ENSKW4J1T2866F7SODRX ON PUBLIC.USER_ENTITY (EMAIL); 